### ISSUE TITLE
Storybook v3

### ISSUE THREAD

**Issue by usulpro** [kadirahq/react-cdk#31]
We can switch to Storybook v3!

Is there anyone interested in this?

**Comment by usulpro** [comment]
### Todo:

- [ ] Switch to `@storybook/react`

- [ ] Use `storybook-deployer`

- [ ] Switch to Jest for testing

- [ ] Use `@storybook/react/demo` for demo components

**Comment by zeroasterisk** [comment]
Yes - I was just about to dust off my favorite `react-cdk`, for a new component... but without storybook3 it makes me wonder if I should...  

It is supposed to always be "updated" but the base template is already month+ behind? 

Please do update so others will continue to trust this great template/dev-kit... I love it... want to keep having it around...

----

I just created a new cdk component, then immediately ran `getstorybook` to update it... 

![ss](https://puu.sh/wMnOJ/e49c835b3a.png)

**Comment by juliomenendez** [comment]
Any update on this?

**Comment by danielduan** [comment]
@UsulPro is this still something we'd like to support going forward?

I think we should either support this full on and have an active maintainer for this or deprecate this to focus other Storybook improvements.

**Comment by usulpro** [comment]
@danielduan I'd like to pull it up to Storybook 3 level. And then integrate it somehow with getstorybook in order to fill the lack when it's running inside an empty folder. Actually, getstorybook and react-cdk use very similar templates, so it could help to maintain it. And we could share own storybook dev tools settings in order to keep it in a good fit.
(We have related work in Storybook cli by @Hypnosphi -- https://github.com/storybooks/storybook/pull/1647)

I guess this project could be useful in some narrow areas:

- creating component libraries
- example && test of manually configured react/storybook app

Maybe somebody who uses it can add other use cases.

On the other hand, I agree with you, we can't do anything without good maintainers team and obviously, I do not have enough time to do it only by myself. We could call the community do somebody want to help or deprecate it otherwise.

**Comment by danielduan** [comment]
I think we should deprecate this. I don't think users lose much if they move to `create-react-app` + `sStorybook/react`

It's been months since Storybook 3 came out but there hasn't been much activity in the issues here and no PRs for the last half year.
